Repository openfun/ashley, pull requests merged in 2020-09, with the labels that each got.

#84 🐛(project) fix Makefile to build frontend assets in bootstrap target
  Makefile
Labels: bug

#87 🐛(back) fix signature max length errors
  CHANGELOG.md
  sandbox/settings.py
  src/ashley/validators.py
  tests/ashley/test_validators.py
Labels: bug, needs review

#82 🔥(project) add quickstart instructions to readme
  README.md
Labels: improvement

#88 💥(lti) replace lti_provider app with the `django-lti-toolbox` dependency
  CHANGELOG.md
  Dockerfile
  MANIFEST.in
  UPGRADE.md
  sandbox/dev_tools/forms.py
  sandbox/dev_tools/views.py
  sandbox/settings.py
  setup.cfg
  src/ashley/auth/backend.py
  src/ashley/factories.py
  src/ashley/machina_extensions/forum/factories.py
  src/ashley/machina_extensions/forum/migrations/0012_auto_20200311_1354.py
  src/ashley/migrations/0001_initial.py
  src/ashley/migrations/0002_auto_20200325_1651.py
  src/ashley/migrations/0003_auto_20200917_1335.py
  src/ashley/models.py
  src/ashley/views.py
  src/lti_provider/__init__.py
  src/lti_provider/admin.py
  src/lti_provider/apps.py
  src/lti_provider/default/__init__.py
  src/lti_provider/default/backend.py
  src/lti_provider/default/handlers.py
  src/lti_provider/defaults.py
  src/lti_provider/exceptions.py
  src/lti_provider/factories.py
  src/lti_provider/launch_params.py
  src/lti_provider/lti.py
  src/lti_provider/migrations/0001_initial.py
  src/lti_provider/migrations/__init__.py
  src/lti_provider/models.py
  src/lti_provider/urls.py
  src/lti_provider/validator.py
  src/lti_provider/views.py
  tests/ashley/test_auth_backend.py
  tests/lti_provider/__init__.py
  tests/lti_provider/test_launch_params.py
  tests/lti_provider/test_lti.py
  tests/lti_provider/test_models.py
  tests/lti_provider/utils.py
  upgrades/1.0.0-beta.3.py
Labels: needs help, needs review
