Repository openfun/ashley, pull requests merged in 2020-12, with the labels that each got.

#106 🌐(backend) update translations
  CHANGELOG.md
  src/ashley/editor/widgets.py
  src/ashley/locale/fr_FR/LC_MESSAGES/django.mo
  src/ashley/locale/fr_FR/LC_MESSAGES/django.po
Labels: improvement, needs review

#98 ✨(search) activate search and fine-tune search experience
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  docker-compose.yml
  sandbox/settings.py
  setup.cfg
  src/ashley/factories.py
  src/ashley/machina_extensions/forum_search/__init__.py
  src/ashley/machina_extensions/forum_search/apps.py
  src/ashley/machina_extensions/forum_search/forms.py
  src/ashley/machina_extensions/forum_search/search_indexes.py
  src/ashley/templates/board_base.html
  src/ashley/templates/forum_search/post_text.txt
  tests/ashley/test_forum_search.py
Labels: improvement

#111 🐛(front) fix Draft.js editor resize issue with static toolbar
  CHANGELOG.md
  src/frontend/js/components/AshleyEditor/index.tsx
  src/frontend/scss/objects/_editor.scss
Labels: bug, needs review

#114 🐛(package) add missing `upgrades` directory in distributed artifacts
  CHANGELOG.md
  Dockerfile
Labels: bug, needs review

#118 ✨(sandbox) add and configure sentry SDK
  CHANGELOG.md
  sandbox/settings.py
  setup.cfg
Labels: feature
