Repository openfun/ashley, pull requests merged in 2021-01, with the labels that each got.

#131 ✨(makefile) create a superuser task
  Makefile
  bin/superuser
Labels: improvement, needs review

#133 ✨(front) add button to insert quotes to the draftjs editor
  CHANGELOG.md
  src/frontend/js/components/AshleyEditor/index.tsx
  src/frontend/scss/_main.scss
  src/frontend/scss/_mixin.scss
  src/frontend/scss/objects/_conversation_topic_detail.scss
  src/frontend/scss/objects/_editor.scss
Labels: improvement, needs review

#132 🐛(search) fix serialization error in search index update
  CHANGELOG.md
  sandbox/settings.py
  src/ashley/defaults.py
  src/ashley/machina_extensions/forum_search/search_indexes.py
  src/ashley/models.py
  src/ashley/templates/forum_search/search.html
  tests/ashley/test_forum_search.py
Labels: bug, needs review

#130 📝 (readme) add access admin and troubleshooting elasticsearch ser…
  README.md
Labels: improvement

#138 ⬆️(front) upgrade draft-js plugins lib
  src/frontend/js/components/AshleyEditor/index.tsx
  src/frontend/js/types/libs/draft-js-static-toolbar-plugin/draft-js-static-toolbar-plugin.d.ts
  src/frontend/package.json
  src/frontend/scss/_main.scss
  src/frontend/yarn.lock
Labels: dependencies, improvement
