Repository openfun/ashley, pull requests merged in 2021-06, with the labels that each got.

#191 🔧(front) upgrade node version
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: needs review

#190 🔧(renovate) update renovate configuration
  renovate.json
Labels: needs review

#192 🩹(factory) fix import user model
  CHANGELOG.md
  src/ashley/factories.py
Labels: improvement, needs review

#193 🔧(circle) target docker version for hub task
  .circleci/config.yml
Labels: bug, needs review

#200 🔧(renovate) ignore js dependencies bootstrap
  renovate.json
Labels: config, needs review

#198 🔧(renovate) ignore python dependencies
  renovate.json
Labels: config, needs review

#204 🩹(forum) fix sorting on sticky and announcements topics
  CHANGELOG.md
  src/ashley/machina_extensions/forum/views.py
  src/ashley/templates/forum_conversation/topic_list.html
  tests/ashley/machina_extensions/forum/test_forum_view.py
Labels: improvement, needs review

#203 🗑️(back) filter search on current lti_context
  CHANGELOG.md
  src/ashley/machina_extensions/forum_search/forms.py
  src/ashley/machina_extensions/forum_search/views.py
  tests/ashley/test_forum_search.py
Labels: WIP, improvement

#205 🔧(sandbox) allowing multiple forums for a same LTIContext on sandbox
  CHANGELOG.md
  sandbox/dev_tools/forms.py
  sandbox/dev_tools/views.py
Labels: config, easy pick, improvement, needs review

#206 ✨(terraform) add terraform configuration
  .gitignore
  Makefile
  bin/state
  bin/terraform
  docker-compose.yml
  env.d/terraform.dist
  terraform/.terraform.lock.hcl
  terraform/cloudfront.tf
  terraform/create_state_bucket/.terraform.lock.hcl
  terraform/create_state_bucket/dynamodb.tf
  terraform/create_state_bucket/output.tf
  terraform/create_state_bucket/provider.tf
  terraform/create_state_bucket/s3.tf
  terraform/create_state_bucket/state.tf
  terraform/create_state_bucket/versions.tf
  terraform/output.tf
  terraform/provider.tf
  terraform/s3.tf
  terraform/state.tf.dist
  terraform/variables.tf
Labels: feature

#209 🔖(ashley) bump version to 1.0.0-beta.6
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: needs review, release
